# Generated by Django 6.1 on 2026-09-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('url', models.URLField(help_text='URL HTTPS direta de uma foto autorizada para divulgação pública.', max_length=1000)),
                ('legenda', models.CharField(blank=True, max_length=250)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('publicada', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'foto pública',
                'verbose_name_plural': 'fotos públicas',
                'ordering': ['ordem', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PaginaPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Escola de Judô Keiko Fukuda', max_length=150)),
                ('historia', models.TextField(blank=True, help_text='História oficial da escola. Deixe vazio enquanto não houver conteúdo aprovado.')),
                ('endereco', models.TextField(blank=True)),
                ('contato', models.CharField(blank=True, help_text='Telefone ou WhatsApp para exibir na página.', max_length=150)),
                ('chamada', models.CharField(blank=True, help_text='Título da divulgação atual.', max_length=150)),
                ('divulgacao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'página pública',
                'verbose_name_plural': 'página pública',
            },
        ),
    ]
