# Generated by Django 6.1 on 2026-09-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_fotopublica_paginapublica'),
    ]

    operations = [
        migrations.AddField(
            model_name='acessoacademia',
            name='administrador',
            field=models.BooleanField(default=False, verbose_name='administrador da academia'),
        ),
    ]
