# Generated by Django 6.1 on 2026-09-06 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0005_atleta_proprio_responsavel'),
        ('portal', '0004_organizar_matriz'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenAcessoResponsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('usado_em', models.DateTimeField(blank=True, null=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_acesso', to='atletas.responsavel')),
            ],
            options={
                'verbose_name': 'link de acesso do responsável',
                'verbose_name_plural': 'links de acesso dos responsáveis',
            },
        ),
    ]
