# Generated by Django 6.1 on 2026-09-08 21:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0003_integracaowhatsapp'),
        ('portal', '0005_tokenacessoresponsavel'),
        ('servicos', '0005_valores_horarios_na_turma'),
    ]

    operations = [
        migrations.CreateModel(
            name='AulaExperimental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(verbose_name='Data e horário')),
                ('vagas', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('inscricoes_abrem', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Abertura das inscrições')),
                ('antecedencia_horas', models.PositiveSmallIntegerField(default=2, verbose_name='Antecedência mínima (horas)')),
                ('fila_habilitada', models.BooleanField(default=True, verbose_name='Habilitar fila de espera')),
                ('ativa', models.BooleanField(default=True)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicos.turma')),
            ],
            options={
                'ordering': ['inicio', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoExperimental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Aceitar agendamentos pelo site')),
                ('vagas_padrao', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Vagas por aula (padrão)')),
                ('antecedencia_horas_padrao', models.PositiveSmallIntegerField(default=2, verbose_name='Antecedência mínima para agendar (horas, padrão)')),
                ('janela_dias', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Liberar agendamento com no máximo (dias de antecedência)')),
                ('fila_habilitada_padrao', models.BooleanField(default=True, verbose_name='Habilitar fila de espera por padrão')),
                ('academia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_experimental', to='academias.academia')),
            ],
            options={
                'verbose_name': 'configuração de aulas experimentais',
                'verbose_name_plural': 'configuração de aulas experimentais',
            },
        ),
        migrations.CreateModel(
            name='InscricaoExperimental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do participante')),
                ('idade', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(120)])),
                ('responsavel', models.CharField(blank=True, max_length=150, verbose_name='Responsável (obrigatório para menores de 18 anos)')),
                ('telefone', models.CharField(max_length=20, verbose_name='WhatsApp com DDD')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('status', models.CharField(choices=[('confirmado', 'Confirmado'), ('espera', 'Fila de espera'), ('cancelado', 'Cancelado'), ('presente', 'Presente'), ('faltou', 'Faltou'), ('convertido', 'Convertido em matrícula')], default='confirmado', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes', to='portal.aulaexperimental')),
            ],
            options={
                'ordering': ['criado_em', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='aulaexperimental',
            constraint=models.CheckConstraint(condition=models.Q(('vagas__gte', 1)), name='experimental_vagas_positivas'),
        ),
        migrations.AddConstraint(
            model_name='inscricaoexperimental',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelado'), _negated=True), fields=('aula', 'nome', 'telefone'), name='experimental_inscricao_unica'),
        ),
    ]
