# Generated by Django 6.1 on 2026-09-08 21:16
import datetime

from django.db import migrations, models


def ajustar_fim_das_aulas(apps, schema_editor):
    """Aulas criadas antes do campo ``fim`` ficaram com o default da migration.
    Dá a elas uma janela mínima de 1h a partir do início."""
    AulaExperimental = apps.get_model('portal', 'AulaExperimental')
    for aula in AulaExperimental.objects.filter(fim__lte=models.F('inicio')):
        aula.fim = aula.inicio + datetime.timedelta(hours=1)
        aula.save(update_fields=['fim'])


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_aulaexperimental_configuracaoexperimental_and_more'),
        ('servicos', '0005_valores_horarios_na_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='aulaexperimental',
            name='fim',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 8, 22, 16, 36, 431231, tzinfo=datetime.timezone.utc), verbose_name='Fim do período'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aulaexperimental',
            name='antecedencia_horas',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Encerrar inscrições quantas horas antes do fim'),
        ),
        migrations.AlterField(
            model_name='aulaexperimental',
            name='inicio',
            field=models.DateTimeField(verbose_name='Início do período'),
        ),
        migrations.RunPython(ajustar_fim_das_aulas, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='aulaexperimental',
            constraint=models.CheckConstraint(condition=models.Q(('fim__gt', models.F('inicio'))), name='experimental_periodo_valido'),
        ),
    ]
