# Generated by Django 6.1 on 2026-09-08 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0003_integracaowhatsapp'),
        ('atletas', '0005_atleta_proprio_responsavel'),
        ('matriculas', '0003_rename_matricula_servico_modalidade'),
        ('portal', '0007_aulaexperimental_fim_and_more'),
        ('servicos', '0005_valores_horarios_na_turma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConviteMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_mensalidade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da mensalidade (R$)')),
                ('dia_vencimento', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Dia de vencimento')),
                ('convidado_nome', models.CharField(blank=True, max_length=150, verbose_name='Nome do aluno (referência)')),
                ('observacao_interna', models.CharField(blank=True, max_length=255, verbose_name='Observação interna')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pendente', 'Aguardando preenchimento'), ('preenchido', 'Preenchido — revisar'), ('ativado', 'Matrícula ativada'), ('cancelado', 'Cancelado')], default='pendente', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('preenchido_em', models.DateTimeField(blank=True, null=True)),
                ('ativado_em', models.DateTimeField(blank=True, null=True)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_matricula', to='academias.academia')),
                ('atleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='atletas.atleta')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='matriculas.matricula')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convites_matricula', to='servicos.modalidade')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convites_matricula', to='servicos.turma')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convites_matricula', to='academias.unidade')),
            ],
            options={
                'verbose_name': 'convite de matrícula',
                'verbose_name_plural': 'convites de matrícula',
                'ordering': ['-criado_em', '-pk'],
            },
        ),
    ]
