# Generated by Django 6.1 on 2026-09-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_convitematricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='convitematricula',
            name='convidado_whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp da família (opcional)'),
        ),
    ]
