# Generated by Django 6.1 on 2026-09-28 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0004_integracaowhatsapp_numero_avisos'),
        ('atletas', '0007_atleta_telefone'),
        ('portal', '0009_convitematricula_convidado_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='convitematricula',
            name='taxa_matricula',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Taxa de matrícula (R$)'),
        ),
        migrations.AddField(
            model_name='convitematricula',
            name='valor_apos_vencimento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor após o vencimento (R$)'),
        ),
        migrations.CreateModel(
            name='FichaMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('convite', 'Convite de matrícula'), ('planilha', 'Planilha do formulário')], max_length=10)),
                ('respondida_em', models.DateTimeField()),
                ('nome_aluno', models.CharField(max_length=150, verbose_name='nome do aluno')),
                ('data_nascimento_informada', models.CharField(blank=True, max_length=30, verbose_name='data de nascimento')),
                ('responsavel_nome', models.CharField(blank=True, max_length=150, verbose_name='nome do responsável')),
                ('telefone_contato', models.CharField(blank=True, max_length=150, verbose_name='telefone para contato')),
                ('email_contato', models.CharField(blank=True, max_length=254, verbose_name='e-mail para contato')),
                ('autorizados_buscar', models.TextField(blank=True, verbose_name='quem está autorizado a buscar')),
                ('vencimento_preferido', models.PositiveSmallIntegerField(blank=True, choices=[(5, 'Até o dia 05 de cada mês'), (10, 'Até o dia 10 de cada mês'), (15, 'Até o dia 15 de cada mês')], null=True, verbose_name='melhor data para o vencimento')),
                ('saude_coracao', models.BooleanField(blank=True, null=True)),
                ('saude_dor_peito', models.BooleanField(blank=True, null=True)),
                ('saude_dor_peito_ultimo_mes', models.BooleanField(blank=True, null=True)),
                ('saude_tontura', models.BooleanField(blank=True, null=True)),
                ('saude_osso_articulacao', models.BooleanField(blank=True, null=True)),
                ('saude_medicacao', models.BooleanField(blank=True, null=True)),
                ('saude_medicacao_qual', models.TextField(blank=True)),
                ('saude_tratamento_pressao', models.BooleanField(blank=True, null=True)),
                ('saude_tratamento_continuo', models.BooleanField(blank=True, null=True)),
                ('saude_tratamento_qual', models.TextField(blank=True)),
                ('saude_cirurgia', models.BooleanField(blank=True, null=True)),
                ('saude_cirurgia_qual', models.TextField(blank=True)),
                ('saude_outra_razao', models.BooleanField(blank=True, null=True)),
                ('saude_outra_razao_qual', models.TextField(blank=True)),
                ('aceitou_termos', models.BooleanField(default=False)),
                ('termos_aceitos', models.TextField(blank=True)),
                ('aceitou_declaracao', models.BooleanField(default=False)),
                ('declaracao_aceita', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_matricula', to='academias.academia')),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_matricula', to='atletas.atleta')),
                ('convite', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ficha', to='portal.convitematricula')),
            ],
            options={
                'verbose_name': 'ficha de matrícula',
                'verbose_name_plural': 'fichas de matrícula',
                'ordering': ['-respondida_em', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('atleta', 'respondida_em'), name='ficha_unica_por_resposta')],
            },
        ),
    ]
