# Generated by Django 6.1 on 2026-09-28 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_ficha_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='convitematricula',
            name='link_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas', to='portal.convitematricula', verbose_name='link permanente de origem'),
        ),
        migrations.AddField(
            model_name='convitematricula',
            name='permanente',
            field=models.BooleanField(default=False, help_text='O mesmo link serve para várias famílias e aparece no site da escola (/matricula/).', verbose_name='link permanente do site'),
        ),
        migrations.AddField(
            model_name='fichamatricula',
            name='responsavel_cpf',
            field=models.CharField(blank=True, max_length=14, verbose_name='CPF do responsável'),
        ),
    ]
