# Generated by Django 6.1 on 2026-08-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('nome_fantasia', models.CharField(blank=True, max_length=150)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ativo', models.BooleanField(default=True)),
                ('criado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
