# Generated by Django 6.1 on 2026-09-06 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('endereco', models.CharField(blank=True, max_length=250)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='academias.academia')),
            ],
            options={
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(fields=('academia', 'nome'), name='unidade_nome_academia')],
            },
        ),
    ]
