# Generated by Django 6.1 on 2026-09-07 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0002_unidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegracaoWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('meta', 'Meta Cloud API'), ('evolution', 'Evolution API')], default='meta', max_length=20)),
                ('numero_whatsapp', models.CharField(blank=True, default='', max_length=20)),
                ('evolution_base_url', models.URLField(blank=True, default='', max_length=300)),
                ('evolution_instance_name', models.CharField(blank=True, default='', max_length=100)),
                ('n8n_webhook_url', models.URLField(blank=True, default='', max_length=300)),
                ('credencial_ref', models.CharField(blank=True, default='', help_text='Nome da variável de ambiente que guarda a credencial deste provedor. O valor da credencial NÃO é armazenado no banco.', max_length=100)),
                ('status_conexao', models.CharField(choices=[('desconectado', 'Desconectado'), ('aguardando_qrcode', 'Aguardando QR Code'), ('conectado', 'Conectado'), ('erro', 'Erro')], default='desconectado', max_length=20)),
                ('ultimo_status', models.CharField(blank=True, default='', max_length=255)),
                ('ultimo_status_em', models.DateTimeField(blank=True, null=True)),
                ('ultima_conexao_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('academia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integracao_whatsapp', to='academias.academia')),
            ],
            options={
                'verbose_name': 'integração de WhatsApp',
                'verbose_name_plural': 'integrações de WhatsApp',
            },
        ),
    ]
