# Generated by Django 6.1 on 2026-09-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0003_integracaowhatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='integracaowhatsapp',
            name='numero_avisos',
            field=models.CharField(blank=True, default='', help_text='Recebe os avisos internos, como matrícula nova para conferir e ativar.', max_length=20, verbose_name='WhatsApp para avisos da escola'),
        ),
    ]
