# Generated by Django 6.1 on 2026-09-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0004_integracaowhatsapp_numero_avisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='declaracao_matricula',
            field=models.TextField(blank=True, help_text='Declaração exibida no fim da ficha de matrícula.', verbose_name='declaração do responsável'),
        ),
        migrations.AddField(
            model_name='academia',
            name='termos_matricula',
            field=models.TextField(blank=True, help_text='Regras da escola exibidas no início da ficha de matrícula.', verbose_name='termos da matrícula'),
        ),
    ]
