# Generated by Django 6.1 on 2026-09-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=200, unique=True)),
                ('ultimo_envio', models.DateTimeField()),
                ('repeticoes', models.PositiveIntegerField(default=0, help_text='Ocorrências desde o último aviso, que não geraram aviso novo.')),
            ],
            options={
                'verbose_name': 'alerta enviado',
                'verbose_name_plural': 'alertas enviados',
                'ordering': ['-ultimo_envio'],
            },
        ),
    ]
