# Generated by Django 6.1 on 2026-09-27 21:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academias', '0004_integracaowhatsapp_numero_avisos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano', models.CharField(default='Gestão Simples', max_length=80)),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor mensal (R$)')),
                ('dia_vencimento', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='dia de vencimento')),
                ('inicio', models.DateField(help_text='A 1ª fatura é a do primeiro vencimento a partir desta data.', verbose_name='início da cobrança')),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('academia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='academias.academia')),
            ],
            options={
                'verbose_name': 'assinatura',
                'verbose_name_plural': 'assinaturas',
            },
        ),
        migrations.CreateModel(
            name='FaturaAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencimento', models.DateField()),
                ('status', models.CharField(choices=[('aberta', 'Em aberto'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], default='aberta', max_length=10)),
                ('pagamento_informado_em', models.DateTimeField(blank=True, help_text='Quando a academia avisou, pelo portal, que já pagou.', null=True)),
                ('pago_em', models.DateTimeField(blank=True, help_text='Quando a plataforma confirmou o pagamento.', null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='assinaturas.assinatura')),
            ],
            options={
                'verbose_name': 'fatura da assinatura',
                'verbose_name_plural': 'faturas da assinatura',
                'ordering': ['-competencia'],
                'constraints': [models.UniqueConstraint(fields=('assinatura', 'competencia'), name='fatura_assinatura_unica_por_mes')],
            },
        ),
    ]
