# Generated by Django 6.1 on 2026-09-28 18:11

from django.db import migrations, models


def converter_dados(apps, schema_editor):
    """Assinatura inativa vira cancelada; fatura "aberta" vira "pendente"
    (a rotina diária marca as vencidas como atrasadas)."""
    Assinatura = apps.get_model("assinaturas", "Assinatura")
    FaturaAssinatura = apps.get_model("assinaturas", "FaturaAssinatura")
    Assinatura.objects.filter(ativa=False).update(status="cancelada")
    FaturaAssinatura.objects.filter(status="aberta").update(status="pendente")


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faturaassinatura',
            options={'ordering': ['-vencimento', '-pk'], 'verbose_name': 'fatura da assinatura', 'verbose_name_plural': 'faturas da assinatura'},
        ),
        migrations.RemoveConstraint(
            model_name='faturaassinatura',
            name='fatura_assinatura_unica_por_mes',
        ),
        migrations.AddField(
            model_name='assinatura',
            name='dias_tolerancia',
            field=models.PositiveSmallIntegerField(default=5, help_text='Dias depois do vencimento com acesso normal; no dia seguinte a eles, a assinatura é suspensa.', verbose_name='dias de tolerância'),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='gateway',
            field=models.CharField(choices=[('woovi', 'Pix (Woovi)')], default='woovi', max_length=20),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='motivo_suspensao',
            field=models.CharField(blank=True, choices=[('inadimplencia', 'Mensalidade em atraso'), ('manual', 'Suspensa pela plataforma')], max_length=20),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='primeiro_vencimento',
            field=models.DateField(blank=True, help_text='Nada vence antes desta data (o período anterior é da implantação). Em branco: o primeiro dia de vencimento a partir do início.', null=True, verbose_name='primeiro vencimento'),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('suspensa', 'Suspensa'), ('cancelada', 'Cancelada')], default='ativa', max_length=10),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='suspensa_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faturaassinatura',
            name='atualizada_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='faturaassinatura',
            name='br_code',
            field=models.TextField(blank=True, verbose_name='Pix copia e cola'),
        ),
        migrations.AddField(
            model_name='faturaassinatura',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='faturaassinatura',
            name='pix_expira_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faturaassinatura',
            name='tipo',
            field=models.CharField(choices=[('mensalidade', 'Mensalidade'), ('implantacao', 'Implantação')], default='mensalidade', max_length=15),
        ),
        migrations.AddField(
            model_name='faturaassinatura',
            name='woovi_charge_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='id da cobrança na Woovi'),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='inicio',
            field=models.DateField(verbose_name='início do serviço'),
        ),
        migrations.AlterField(
            model_name='faturaassinatura',
            name='pago_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faturaassinatura',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('atrasada', 'Atrasada'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], default='pendente', max_length=10),
        ),
        migrations.RunPython(converter_dados, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='assinatura',
            name='ativa',
        ),
        migrations.AddConstraint(
            model_name='faturaassinatura',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'mensalidade')), fields=('assinatura', 'competencia'), name='fatura_assinatura_unica_por_mes'),
        ),
        migrations.RemoveField(
            model_name='faturaassinatura',
            name='pagamento_informado_em',
        ),
    ]
