# Generated by Django 6.1 on 2026-09-29 17:17

import integracoes.woovi.credenciais
from django.db import migrations, models
from django.conf import settings


def preservar_origem(apps, schema_editor):
    apps.get_model('assinaturas', 'FaturaAssinatura').objects.using(schema_editor.connection.alias).all().update(
        credencial_ref='WOOVI_APP_ID', api_base_url=settings.WOOVI_BASE_URL.rstrip('/'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0002_status_woovi_e_tolerancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturaassinatura',
            name='api_base_url',
            field=models.URLField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='faturaassinatura',
            name='credencial_ref',
            field=models.CharField(default='WOOVI_APP_ID', editable=False, max_length=100),
        ),
        migrations.RunPython(preservar_origem, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='faturaassinatura', name='credencial_ref',
            field=models.CharField(default=integracoes.woovi.credenciais.referencia_plataforma, editable=False, max_length=100),
        ),
    ]
