"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.
"""

import os
from pathlib import Path

from dotenv import load_dotenv


# =============================================================================
# BASE
# =============================================================================

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# =============================================================================
# SECURITY
# =============================================================================

SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-dev-only",
)

DEBUG = os.getenv(
    "DJANGO_DEBUG",
    "true",
).lower() == "true"


ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "ALLOWED_HOSTS",
        "localhost,127.0.0.1",
    ).split(",")
    if host.strip()
]


# =============================================================================
# APPLICATIONS
# =============================================================================

INSTALLED_APPS = [
    "portal",

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "academias",
    "atletas",
    "modalidades",
    "matriculas",
    "financeiro",
]


# =============================================================================
# MIDDLEWARE
# =============================================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# =============================================================================
# URLS / WSGI
# =============================================================================

ROOT_URLCONF = "config.urls"

WSGI_APPLICATION = "config.wsgi.application"


# =============================================================================
# TEMPLATES
# =============================================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# =============================================================================
# DATABASE
#
# Local:
# DB_ENGINE=sqlite
#
# AWS:
# DB_ENGINE=postgresql
# =============================================================================

DB_ENGINE = os.getenv(
    "DB_ENGINE",
    "sqlite",
).lower()


if DB_ENGINE == "postgresql":

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",

            "NAME": os.getenv(
                "POSTGRES_DB",
            ),

            "USER": os.getenv(
                "POSTGRES_USER",
            ),

            "PASSWORD": os.getenv(
                "POSTGRES_PASSWORD",
            ),

            "HOST": os.getenv(
                "POSTGRES_HOST",
                "127.0.0.1",
            ),

            "PORT": os.getenv(
                "POSTGRES_PORT",
                "5432",
            ),

            "CONN_MAX_AGE": int(
                os.getenv(
                    "DB_CONN_MAX_AGE",
                    "60",
                )
            ),

            "OPTIONS": {
                "sslmode": os.getenv(
                    "POSTGRES_SSLMODE",
                    "prefer",
                ),
            },
        }
    }

else:

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# =============================================================================
# PASSWORD VALIDATION
# =============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# =============================================================================
# INTERNATIONALIZATION
# =============================================================================

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# =============================================================================
# STATIC FILES
# =============================================================================

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"


# =============================================================================
# MEDIA FILES
# =============================================================================

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"


# =============================================================================
# DEFAULT PRIMARY KEY
# =============================================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# =============================================================================
# AUTH
# =============================================================================

LOGIN_URL = "portal:login"

LOGIN_REDIRECT_URL = "portal:dashboard"

LOGOUT_REDIRECT_URL = "portal:login"


# =============================================================================
# DJANGO MESSAGES / BOOTSTRAP
# =============================================================================

from django.contrib.messages import constants as messages  # noqa: E402

MESSAGE_TAGS = {
    messages.ERROR: "danger",
}


# =============================================================================
# EMAIL
#
# Enquanto o sistema estiver em desenvolvimento, os e-mails são exibidos
# no console.
# =============================================================================

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}


# =============================================================================
# ASAAS
# =============================================================================

ASAAS_API_KEY = os.getenv(
    "ASAAS_API_KEY",
    "",
)

ASAAS_BASE_URL = os.getenv(
    "ASAAS_BASE_URL",
    "https://api-sandbox.asaas.com/v3",
)

ASAAS_WEBHOOK_TOKEN = os.getenv(
    "ASAAS_WEBHOOK_TOKEN",
    "",
)

# Em produção (DEBUG=False) o webhook do Asaas só aceita eventos com o
# cabeçalho 'asaas-access-token' válido. Se o token não estiver configurado,
# o endpoint recusa todo POST (503) em vez de aceitar qualquer chamada.
# Em desenvolvimento (DEBUG=True) o comportamento permissivo é mantido.
ASAAS_WEBHOOK_REQUIRE_TOKEN = os.getenv(
    "ASAAS_WEBHOOK_REQUIRE_TOKEN",
    "true" if not DEBUG else "false",
).lower() == "true"


# =============================================================================
# META / WHATSAPP CLOUD API
# =============================================================================

META_WHATSAPP_TOKEN = os.getenv(
    "META_WHATSAPP_TOKEN",
    "",
)

META_WHATSAPP_PHONE_NUMBER_ID = os.getenv(
    "META_WHATSAPP_PHONE_NUMBER_ID",
    "",
)

META_WHATSAPP_WABA_ID = os.getenv(
    "META_WHATSAPP_WABA_ID",
    "",
)

META_WHATSAPP_API_VERSION = os.getenv(
    "META_WHATSAPP_API_VERSION",
    "v25.0",
)

META_WHATSAPP_WEBHOOK_VERIFY_TOKEN = os.getenv(
    "META_WHATSAPP_WEBHOOK_VERIFY_TOKEN",
    "",
)


# =============================================================================
# N8N (contrato preparado — não acionado no fluxo de lembretes ainda)
# =============================================================================

N8N_WEBHOOK_URL = os.getenv("N8N_WEBHOOK_URL", "")
N8N_TOKEN = os.getenv("N8N_TOKEN", "")
N8N_TIMEOUT = int(os.getenv("N8N_TIMEOUT", "10"))


# =============================================================================
# EVOLUTION API
#
# A API key de cada academia NÃO fica aqui nem no banco: fica numa variável
# de ambiente cujo NOME é guardado em IntegracaoWhatsApp.credencial_ref
# (ex.: EVOLUTION_API_KEY_KEIKO). Não crie uma EVOLUTION_API_KEY global.
# =============================================================================

EVOLUTION_TIMEOUT = int(os.getenv("EVOLUTION_TIMEOUT", "15"))

# Webhook opcional de eventos de conexão (connection.update / qrcode.updated).
EVOLUTION_WEBHOOK_TOKEN = os.getenv("EVOLUTION_WEBHOOK_TOKEN", "")
EVOLUTION_WEBHOOK_REQUIRE_TOKEN = os.getenv(
    "EVOLUTION_WEBHOOK_REQUIRE_TOKEN",
    "true" if not DEBUG else "false",
).lower() == "true"


# =============================================================================
# LEMBRETES DE COBRANÇA — chaves de ativação da FASE 2
#
# Ambas começam desligadas: o lembrete continua exatamente como hoje
# (envia link de pagamento via provedor Meta). Quando a automação estiver
# pronta, ligue por ambiente.
# =============================================================================

# Gera/garante a cobrança Asaas (UNDEFINED) antes de enviar o lembrete,
# para o Pix copia-e-cola já existir na mensagem.
LEMBRETES_GERAM_COBRANCA_ASAAS = os.getenv(
    "LEMBRETES_GERAM_COBRANCA_ASAAS",
    "false",
).lower() == "true"

# Envia o payload ao n8n (que aciona a Evolution) em vez do provedor Meta.
LEMBRETES_ENVIAM_N8N = os.getenv(
    "LEMBRETES_ENVIAM_N8N",
    "false",
).lower() == "true"


# =============================================================================
# SITE
# =============================================================================

SITE_URL = os.getenv(
    "SITE_URL",
    "http://127.0.0.1:8000",
).rstrip("/")


# =============================================================================
# PROXY / NGINX
# =============================================================================

SECURE_PROXY_SSL_HEADER = (
    "HTTP_X_FORWARDED_PROTO",
    "https",
)


# =============================================================================
# CSRF
# =============================================================================

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CSRF_TRUSTED_ORIGINS",
        "",
    ).split(",")
    if origin.strip()
]


# =============================================================================
# PRODUCTION SECURITY
#
# Estas opções são ativadas apenas quando DEBUG=False.
# SSL_REDIRECT fica configurável porque neste momento você ainda pode estar
# acessando a aplicação apenas por HTTP/IP.
# =============================================================================

if not DEBUG:

    SESSION_COOKIE_SECURE = os.getenv(
        "SESSION_COOKIE_SECURE",
        "false",
    ).lower() == "true"

    CSRF_COOKIE_SECURE = os.getenv(
        "CSRF_COOKIE_SECURE",
        "false",
    ).lower() == "true"

    SECURE_SSL_REDIRECT = os.getenv(
        "SECURE_SSL_REDIRECT",
        "false",
    ).lower() == "true"

    SECURE_HSTS_SECONDS = int(
        os.getenv(
            "SECURE_HSTS_SECONDS",
            "0",
        )
    )

    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv(
        "SECURE_HSTS_INCLUDE_SUBDOMAINS",
        "false",
    ).lower() == "true"

    SECURE_HSTS_PRELOAD = os.getenv(
        "SECURE_HSTS_PRELOAD",
        "false",
    ).lower() == "true"