# Generated by Django 6.1 on 2026-08-21 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academias', '0001_initial'),
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencimento', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada'), ('isenta', 'Isenta')], default='pendente', max_length=20)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('asaas_payment_id', models.CharField(blank=True, max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensalidades', to='academias.academia')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensalidades', to='matriculas.matricula')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('matricula', 'competencia'), name='mensalidade_unica_por_competencia')],
            },
        ),
    ]
