# Generated by Django 6.1 on 2026-09-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_mensalidade_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalidade',
            name='asaas_bank_slip_url',
            field=models.URLField(blank=True, help_text='PDF do boleto, quando a cobrança aceita esse meio.', max_length=300),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='asaas_invoice_url',
            field=models.URLField(blank=True, help_text='Página de pagamento hospedada pelo Asaas (Pix, boleto ou cartão).', max_length=300),
        ),
    ]
