# Generated by Django 6.1 on 2026-09-06 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_mensalidade_asaas_bank_slip_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LembreteCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estagio', models.CharField(choices=[('5_dias', '5 dias antes do vencimento'), ('1_dia', '1 dia antes do vencimento'), ('vencimento', 'No dia do vencimento'), ('atrasada', 'Mensalidade atrasada')], max_length=20)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('mensalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lembretes', to='financeiro.mensalidade')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('mensalidade', 'estagio'), name='lembrete_unico_por_estagio')],
            },
        ),
    ]
