# Generated by Django 6.1 on 2026-09-07 18:10

from django.db import migrations, models


def marcar_enviados_existentes(apps, schema_editor):
    """Registros anteriores só existiam em caso de sucesso: marca-os como
    'enviado' para que enviar_lembretes não os reprocesse."""
    LembreteCobranca = apps.get_model('financeiro', 'LembreteCobranca')
    LembreteCobranca.objects.filter(enviado_em__isnull=False).update(status='enviado')


def reverter(apps, schema_editor):
    LembreteCobranca = apps.get_model('financeiro', 'LembreteCobranca')
    LembreteCobranca.objects.update(status='pendente')


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_lembretecobranca'),
    ]

    operations = [
        migrations.AddField(
            model_name='lembretecobranca',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='lembretecobranca',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='lembretecobranca',
            name='provider_message_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='lembretecobranca',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('erro', 'Erro')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='lembretecobranca',
            name='tentativas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lembretecobranca',
            name='ultimo_erro',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='lembretecobranca',
            name='enviado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(marcar_enviados_existentes, reverter),
    ]
