# Generated by Django 6.1 on 2026-09-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_lembretecobranca_atualizado_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensalidade',
            name='asaas_bank_slip_url',
        ),
        migrations.RemoveField(
            model_name='mensalidade',
            name='asaas_invoice_url',
        ),
        migrations.RemoveField(
            model_name='mensalidade',
            name='asaas_payment_id',
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='woovi_br_code',
            field=models.TextField(blank=True, help_text='Pix copia e cola.'),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='woovi_correlation_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='woovi_expira_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='woovi_link_pagamento',
            field=models.URLField(blank=True, help_text='Página de pagamento hospedada pela Woovi.', max_length=500),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='woovi_qrcode_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
