# Generated by Django 6.1 on 2026-09-26 16:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0003_integracaowhatsapp'),
        ('financeiro', '0006_troca_asaas_por_woovi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=255, unique=True)),
                ('tipo', models.CharField(max_length=80)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('recebido', 'Recebido'), ('processado', 'Processado'), ('ignorado', 'Ignorado'), ('erro', 'Erro')], default='recebido', max_length=10)),
                ('erro', models.TextField(blank=True)),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'evento de webhook',
                'verbose_name_plural': 'eventos de webhook',
                'ordering': ['-recebido_em', '-pk'],
            },
        ),
        migrations.RemoveField(
            model_name='mensalidade',
            name='woovi_br_code',
        ),
        migrations.RemoveField(
            model_name='mensalidade',
            name='woovi_correlation_id',
        ),
        migrations.RemoveField(
            model_name='mensalidade',
            name='woovi_expira_em',
        ),
        migrations.RemoveField(
            model_name='mensalidade',
            name='woovi_link_pagamento',
        ),
        migrations.RemoveField(
            model_name='mensalidade',
            name='woovi_qrcode_url',
        ),
        migrations.CreateModel(
            name='ContaRecebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_chave', models.CharField(choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ'), ('email', 'E-mail'), ('telefone', 'Celular'), ('aleatoria', 'Chave aleatória')], max_length=10)),
                ('pix_key', models.CharField(max_length=100, verbose_name='chave Pix')),
                ('ativa', models.BooleanField(default=True)),
                ('saque_bloqueado', models.BooleanField(default=False, help_text='O provedor recusou transferir para esta chave (chave inválida ou restrita).')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('desativada_em', models.DateTimeField(blank=True, null=True)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_recebimento', to='academias.academia')),
                ('criada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('desativada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conta de recebimento',
                'verbose_name_plural': 'contas de recebimento',
                'ordering': ['-criada_em', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='CobrancaPix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_id', models.CharField(max_length=100, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('paga', 'Paga'), ('expirada', 'Expirada'), ('cancelada', 'Cancelada')], db_index=True, default='ativa', max_length=10)),
                ('br_code', models.TextField(help_text='Pix copia e cola.')),
                ('link_pagamento', models.URLField(blank=True, max_length=500)),
                ('expira_em', models.DateTimeField()),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('mensalidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobrancas_pix', to='financeiro.mensalidade')),
                ('conta_recebimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobrancas_pix', to='financeiro.contarecebimento')),
            ],
            options={
                'verbose_name': 'cobrança Pix',
                'verbose_name_plural': 'cobranças Pix',
                'ordering': ['-criada_em', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Repasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pix_key_destino', models.CharField(max_length=100)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, help_text='Valor efetivamente enviado (saldo disponível no momento do saque).', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluida', 'Concluída'), ('falha', 'Falha — nova tentativa agendada'), ('requer_atencao', 'Requer atenção')], db_index=True, default='pendente', max_length=15)),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('proxima_tentativa_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('saldo_novo_pendente', models.BooleanField(default=False, help_text='Chegou pagamento enquanto este saque estava em andamento: ao concluir, outro repasse é aberto para o saldo novo.')),
                ('reconciliar', models.BooleanField(default=False, help_text='O último pedido de saque terminou sem resposta: conferir o extrato antes de pedir de novo (o saque não é idempotente).')),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('end_to_end_id', models.CharField(blank=True, max_length=100)),
                ('erro', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('processado_em', models.DateTimeField(blank=True, help_text='Quando o saque foi pedido ao provedor.', null=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repasses', to='academias.academia')),
                ('conta_recebimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repasses', to='financeiro.contarecebimento')),
            ],
            options={
                'ordering': ['-criado_em', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='contarecebimento',
            constraint=models.UniqueConstraint(condition=models.Q(('ativa', True)), fields=('academia',), name='uma_conta_recebimento_ativa_por_academia'),
        ),
        migrations.AddConstraint(
            model_name='cobrancapix',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ativa')), fields=('mensalidade',), name='uma_cobranca_pix_ativa_por_mensalidade'),
        ),
        migrations.AddConstraint(
            model_name='repasse',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pendente', 'processando', 'falha'])), fields=('conta_recebimento',), name='um_repasse_aberto_por_conta'),
        ),
    ]
