# Generated by Django 6.1 on 2026-09-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_recebimento_cobranca_pix_repasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrancapix',
            name='creditado_em',
            field=models.DateTimeField(blank=True, help_text='Quando o líquido foi creditado na subconta.', null=True),
        ),
        migrations.AddField(
            model_name='cobrancapix',
            name='credito_incerto',
            field=models.BooleanField(default=False, help_text='O último pedido de crédito terminou sem resposta: conferir o extrato da subconta antes de pedir de novo (o crédito não é idempotente).'),
        ),
        migrations.AddField(
            model_name='cobrancapix',
            name='taxa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Taxa da Woovi sobre este Pix (vem no aviso de pagamento). Se ficar vazia, o repasse para em 'Requer atenção' até ser informada.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cobrancapix',
            name='valor_liquido',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor pago menos a taxa: o que é creditado na subconta da academia.', max_digits=10, null=True),
        ),
    ]
