# Generated by Django 6.1 on 2026-09-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_credito_liquido_na_subconta'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mensalidade',
            name='mensalidade_unica_por_competencia',
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='tipo',
            field=models.CharField(choices=[('mensalidade', 'Mensalidade'), ('taxa_matricula', 'Taxa de matrícula')], default='mensalidade', max_length=20),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='valor_apos_vencimento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor após o vencimento'),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='mensalidade',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'mensalidade')), fields=('matricula', 'competencia'), name='mensalidade_unica_por_competencia'),
        ),
        migrations.AddConstraint(
            model_name='mensalidade',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'taxa_matricula')), fields=('matricula',), name='uma_taxa_matricula_por_matricula'),
        ),
    ]
