# Generated by Django 6.1 on 2026-09-29 17:17

import hashlib
from django.db import migrations, models
from django.conf import settings


def preservar_origem(apps, schema_editor):
    apps.get_model('financeiro', 'ContaRecebimento').objects.using(schema_editor.connection.alias).all().update(
        modelo_recebimento='legado_subconta', credencial_ref='WOOVI_APP_ID',
        api_base_url=settings.WOOVI_BASE_URL.rstrip('/'),
        credencial_fingerprint=hashlib.sha256(settings.WOOVI_APP_ID.encode()).hexdigest() if settings.WOOVI_APP_ID else '',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0005_textos_ficha_matricula'),
        ('financeiro', '0009_taxa_matricula_e_valor_apos_vencimento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrancapix',
            name='modelo_recebimento',
            field=models.CharField(choices=[('legado_subconta', 'Subconta legada'), ('conta_propria', 'Conta própria')], default='legado_subconta', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='cobrancapix',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contarecebimento',
            name='api_base_url',
            field=models.URLField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='contarecebimento',
            name='conectada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contarecebimento',
            name='credencial_fingerprint',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='contarecebimento',
            name='credencial_ref',
            field=models.CharField(default='WOOVI_APP_ID', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='contarecebimento',
            name='modelo_recebimento',
            field=models.CharField(choices=[('legado_subconta', 'Subconta legada'), ('conta_propria', 'Conta própria')], default='legado_subconta', max_length=20),
        ),
        migrations.AddField(
            model_name='contarecebimento',
            name='onboarding_correlation_id',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='contarecebimento',
            name='onboarding_status',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='contarecebimento',
            name='onboarding_url',
            field=models.URLField(blank=True, editable=False, max_length=1000),
        ),
        migrations.AddField(
            model_name='contarecebimento',
            name='provider',
            field=models.CharField(default='woovi', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='contarecebimento',
            name='provider_account_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contarecebimento',
            name='status',
            field=models.CharField(choices=[('nao_configurada', 'Não configurada'), ('configurando', 'Configuração em andamento'), ('aguardando', 'Aguardando validação'), ('conectada', 'Conectada'), ('erro', 'Erro')], default='nao_configurada', max_length=20),
        ),
        migrations.AddField(
            model_name='contarecebimento',
            name='taxa_ciente_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contarecebimento',
            name='pix_key',
            field=models.CharField(blank=True, max_length=100, verbose_name='chave Pix'),
        ),
        migrations.AlterField(
            model_name='contarecebimento',
            name='tipo_chave',
            field=models.CharField(blank=True, choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ'), ('email', 'E-mail'), ('telefone', 'Celular'), ('aleatoria', 'Chave aleatória')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='contarecebimento',
            constraint=models.UniqueConstraint(condition=models.Q(('modelo_recebimento', 'conta_propria')), fields=('academia',), name='uma_conta_propria_por_academia'),
        ),
        migrations.RunPython(preservar_origem, migrations.RunPython.noop),
    ]
