# Generated by Django 6.1 on 2026-09-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0010_contas_proprias'),
    ]

    operations = [
        migrations.AddField(
            model_name='contarecebimento',
            name='credencial_cifrada',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='contarecebimento',
            name='webhook_configurado_em',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
