# Generated by Django 6.1 on 2026-08-21 00:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0002_atleta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsavel',
            old_name='criado',
            new_name='criado_em',
        ),
        migrations.AddField(
            model_name='atleta',
            name='cpf',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='atleta',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atleta',
            name='faixa',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='atleta',
            name='nome',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='cpf',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='whatsapp',
            field=models.CharField(max_length=20),
        ),
    ]
