# Generated by Django 6.1 on 2026-09-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0003_rename_criado_responsavel_criado_em_atleta_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='asaas_customer_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
