# Generated by Django 6.1 on 2026-09-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0004_responsavel_asaas_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='proprio_responsavel',
            field=models.BooleanField(default=False, verbose_name='o aluno é o responsável financeiro'),
        ),
    ]
