# Generated by Django 6.1 on 2026-09-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0005_atleta_proprio_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsavel',
            name='asaas_customer_id',
        ),
    ]
