# Generated by Django 6.1 on 2026-09-27 18:36

from django.db import migrations, models


def copiar_whatsapp_do_proprio_responsavel(apps, schema_editor):
    """Aluno que já era o próprio responsável: o WhatsApp dele estava só no
    Responsavel. Passa a ficar também no cadastro do aluno."""
    Atleta = apps.get_model('atletas', 'Atleta')
    for atleta in Atleta.objects.filter(
        proprio_responsavel=True, telefone='', responsavel_financeiro__isnull=False,
    ).select_related('responsavel_financeiro'):
        atleta.telefone = atleta.responsavel_financeiro.whatsapp or ''
        atleta.save(update_fields=['telefone'])


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0006_remove_asaas_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='telefone / WhatsApp'),
        ),
        migrations.RunPython(copiar_whatsapp_do_proprio_responsavel, migrations.RunPython.noop),
    ]
