# Generated by Django 6.1 on 2026-09-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0007_atleta_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='bloqueado_ate',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='senha',
            field=models.CharField(blank=True, editable=False, max_length=128),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='senha_definida_em',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='tentativas_login',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
