# Generated by Django 6.1 on 2026-08-21 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academias', '0001_initial'),
        ('atletas', '0003_rename_criado_responsavel_criado_em_atleta_cpf_and_more'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_mensalidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dia_vencimento', models.PositiveSmallIntegerField(default=10)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='academias.academia')),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='atletas.atleta')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='servicos.servico')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='servicos.turma')),
            ],
        ),
    ]
