# Generated by Django 6.1 on 2026-09-06 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0002_unidade'),
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='academias.unidade'),
        ),
    ]
