# Generated by Django 6.1 on 2026-09-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0003_rename_matricula_servico_modalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='primeiro_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='primeiro vencimento'),
        ),
    ]
