# Generated by Django 6.1 on 2026-09-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0004_matricula_primeiro_vencimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='taxa_matricula',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='taxa de matrícula'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='valor_apos_vencimento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor após o vencimento'),
        ),
    ]
