# Generated by Django 6.1 on 2026-09-06 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0002_unidade'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='academias.unidade'),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('graduacao', models.CharField(blank=True, max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores', to='academias.academia')),
            ],
            options={
                'verbose_name_plural': 'professores',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='turma',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='servicos.professor', verbose_name='professor responsável'),
        ),
    ]
