# Generated by Django 6.1 on 2026-09-06 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0002_unidade'),
        ('servicos', '0002_turma_unidade_professor_turma_docente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={'verbose_name': 'modalidade', 'verbose_name_plural': 'modalidades'},
        ),
        migrations.CreateModel(
            name='Graduacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academias.academia')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='graduacoes', to='servicos.servico')),
            ],
            options={
                'verbose_name': 'graduação / faixa',
                'verbose_name_plural': 'graduações / faixas',
                'ordering': ['modalidade__nome', 'ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='professor',
            name='faixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='servicos.graduacao', verbose_name='Modalidade e faixa'),
        ),
        migrations.AddConstraint(
            model_name='graduacao',
            constraint=models.UniqueConstraint(fields=('modalidade', 'nome'), name='graduacao_modalidade_nome'),
        ),
    ]
