# Generated by Django 6.1 on 2026-09-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_valores_horarios_na_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='taxa_matricula',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gerada quando a matrícula é ativada. Em branco: sem taxa.', max_digits=10, null=True, verbose_name='taxa de matrícula'),
        ),
        migrations.AddField(
            model_name='turma',
            name='valor_apos_vencimento',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cobrado a partir do dia seguinte ao vencimento. Em branco: o valor não muda.', max_digits=10, null=True, verbose_name='valor após o vencimento'),
        ),
    ]
